// GENERATED by scripts/build-tokens.mjs — edit tokens/*.json instead.
// These names must match the [data-accent] / [data-gray] blocks in
// tokens.css, which is why both come out of the same build.

export const ACCENT_COLORS = [
  'red',
  'orange',
  'amber',
  'yellow',
  'lime',
  'green',
  'emerald',
  'teal',
  'cyan',
  'sky',
  'blue',
  'indigo',
  'violet',
  'purple',
  'fuchsia',
  'pink',
  'rose',
] as const
export type AccentColor = (typeof ACCENT_COLORS)[number]

export const GRAY_COLORS = [
  'slate',
  'gray',
  'zinc',
  'neutral',
  'stone',
  'mauve',
  'olive',
  'mist',
  'taupe',
] as const
export type GrayColor = (typeof GRAY_COLORS)[number]
